//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JsonPathParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.JPath.Parsers {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JsonPathParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IJsonPathParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.jsonpath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonpath([NotNull] JsonPathParser.JsonpathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.jsonpath_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonpath_([NotNull] JsonPathParser.Jsonpath_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.jsonpath__"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonpath__([NotNull] JsonPathParser.Jsonpath__Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.jsonpath_subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonpath_subscript([NotNull] JsonPathParser.Jsonpath_subscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.subscriptables"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptables([NotNull] JsonPathParser.SubscriptablesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.subscriptableArguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptableArguments([NotNull] JsonPathParser.SubscriptableArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.subscriptableBareword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptableBareword([NotNull] JsonPathParser.SubscriptableBarewordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.jsonPath_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonPath_identifier([NotNull] JsonPathParser.JsonPath_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.subscriptable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptable([NotNull] JsonPathParser.SubscriptableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.sliceable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceable([NotNull] JsonPathParser.SliceableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.sliceableLeft"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceableLeft([NotNull] JsonPathParser.SliceableLeftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.sliceableRight"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceableRight([NotNull] JsonPathParser.SliceableRightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.sliceableBinary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceableBinary([NotNull] JsonPathParser.SliceableBinaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] JsonPathParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.binaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryOperator([NotNull] JsonPathParser.BinaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJson([NotNull] JsonPathParser.JsonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObj([NotNull] JsonPathParser.ObjContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] JsonPathParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] JsonPathParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsonPathParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] JsonPathParser.ValueContext context);
}
} // namespace Bb.JPath.Parsers
